name: DeployDemoToGitHubPages
env:
  PUBLISH_DIR: site/Site/bin/Release/net9.0/publish/wwwroot

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Deploy Site to GitHub Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9'

    - name: Publish app
      run: cd site/Site && dotnet publish -c Release

    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v1.5.1
      with:
        target_branch: gh-pages
        build_dir: ${{ env.PUBLISH_DIR }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
